### ISSUE TITLE
Bump upper bound of protobuf dependencies

### ISSUE THREAD

**Issue by mateenkasim** [authzed/authzed-py#113]
`protobuf` v4.25 came out last month, so it'd be awesome if this client allowed v25 too. Not interested in updating the lockfile, just bumping the upper bound as was done in [my fork here](https://github.com/mateenkasim/authzed-py/commit/ac18e226f09a5e1ea3732c563744cd6330a7b383).

Let me know if you'd like me to make a PR or if you'd rather do some testing beforehand. It works as expected in my own small use case, which resolved the `protobuf` version to `4.25.1` due to another package's stricter requirements (`>=4.25.0`).

**Comment by jzelinskie** [comment]
Using a range is certainly a good idea and we'd appreciate a PR to add one.

I think the safest range would be something like `>=4.23,<5`, so that if there's a major, breaking release for protobuf, our upper-bound is still correct

**Comment by intentionally-left-nil** [comment]
What would it take to support protobuf 5 as well?
