### ISSUE TITLE
Client initialization throws an error if run in a sub thread

### ISSUE THREAD

**Issue by DanieleIsoni** [authzed/authzed-py#33]
In the client initialization it is run the following line to decide whether to run grpc async or not. 
https://github.com/authzed/authzed-py/blob/0e6b9715d05db07d15ac5bc99aa55bdf77ac23c8/authzed/api/v1/__init__.py#L52

Unfortunately this the `asyncio.get_event_loop()` throws the following error if run in a sub-thread.
```
RuntimeError: There is no current event loop in thread 'Thread-2'.
```

Also, the `get_event_loop` function creates an event loop if it does not find any, and this is not a great thing if run in a synchronous environment. Moreover in the asyncio documentation is said that `get_event_loop` is deprecated since python 3.10 (see https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_event_loop), and they suggest using `get_running_loop` instead.

## My environment
- python 3.9.9
- authzed 0.4.2

## How to reproduce
The following code is a fast way to reproduce the problem
```
import threading
from authzed.api.v1 import Client
from grpcutil import insecure_bearer_token_credentials

def instantiate_client():
    Client("localhost:50051", insecure_bearer_token_credentials("some-token"))

th = threading.Thread(target=instantiate_client)
th.start()
```

## Possible solution
- create two different classes, Client and AsyncClient.
- change how `channelfn` is set with something like:
```
try:
    asyncio.get_running_loop()
    channelfn = grpc.aio.secure_channel
except RuntimeError:
    channelfn = grpc.secure_channel
```

**Comment by jzelinskie** [comment]
Hey there!

Thanks for the report. We used to have two separate clients, but many folks ended up not noticing and wasting lots of time being confused why things weren't working when they were using the wrong client.

Your suggestion for using `get_running_loop()` seems like the best way to move forward without any user disruption.
