### ISSUE TITLE
Allow newer versions of typing_extensions

### ISSUE THREAD

**Issue by jakul** [authzed/authzed-py#37]
This repo [limits typing_extensions to v3](https://github.com/authzed/authzed-py/blob/a86f55579a79b6c83ee4dea56ef1c154083f5c29/pyproject.toml#L22) with the `^3.7.4` constraint, but the current version has been bumped to 4. This [looks to be a non-breaking change](https://github.com/python/typing/blob/95c9c2bab2034f0359e8457360d93a288a65e55d/typing_extensions/CHANGELOG#L36-L41).

I'd like to use both `authzed-py` and `typing_extensions>=4.0.0` in a project.

**Comment by jakul** [comment]
I'm glad to see the branch with this change in has been merged to main. 

What's the release process to get a new version onto Pypi?

**Comment by samkim** [comment]
Apologies for the delay. v0.5.1 was just published and has the update. 
https://pypi.org/project/authzed/0.5.1/
