### ISSUE TITLE
Allow newer versions of `protobuf` 

### ISSUE THREAD

**Issue by jbergler** [authzed/authzed-py#67]
Hello, this project pins currently restricts `protobuf` to `v20` with a `3.20.3` constraint.
We'd like to use v21 or v22 in our project alongside this package.

There are some minor breaking changes noted in the [v21 release](https://github.com/protocolbuffers/protobuf/releases/tag/v21.0) for python [here](https://protobuf.dev/news/2022-05-06/#python-updates)

They don't look particularly major, but I'm not sure if any of those notes are of interest to this project.

An update to the dependency would be greatly appreciated.

**Comment by samkim** [comment]
Fixed by https://github.com/authzed/authzed-py/pull/68

**Comment by samkim** [comment]
@jbergler just cut a release with the update: https://github.com/authzed/authzed-py/releases/tag/v0.8.0

**Comment by jbergler** [comment]
Thank you!
